### ISSUE TITLE
[BUG ?] computing single trials  ERSP returns an empty structure

### ISSUE THREAD

**Issue by claire-braboszcz** [LIMO-EEG-Toolbox/Open-Contributions#1]
Hi there, 

The function limo_create_single_trials  is returning an empty structure when computing ERSPs.  It is working fine though for ERPs and spectrum. I could not figure out what's wrong. I used the function through the GUI on Matlab R2013a running on Ubuntu 16.04.
Can you confirm it is a bug ? Else I will try to sort out what's wrong with my data !

Claire

**Comment by CPernet** [comment]
Hi Claire

last time I tried it - it ran just fine
https://github.com/LIMO-EEG-Toolbox/limo_eeg/blob/master/limo_create_single_trials.m

as you can see from the code, it simply calls std_precomp ; but 'made easy' from your EEG.set. You can check by loading one EEG.set into EEGLAB go to study --> precompute --> ERSP, save single trials @nucleuscub might be able to help if that still doesn't work

**Comment by claire-braboszcz** [comment]
Thanks Cyril, it is working indeed when directly using EEGlab..
(sorry, just realized my earlier reply using my email has not been pushed on to github)
